#cloud-config
autoinstall:
  version: 1
  shutdown: poweroff
  updates: all
  source:
    id: ubuntu-desktop-minimal
  user-data:
    users: [""]
    disable_root: true
  apt:
    sources:
      microsoft-prod.list:
        source: "deb https://packages.microsoft.com/ubuntu/24.04/prod noble main"
        keyid: BC52 8686 B50D 79E3 39D3  721C EB3E 94AD BE12 29CF
      microsoft-edge-stable.list:
        source: "deb https://packages.microsoft.com/repos/edge stable main"
        keyid: BC52 8686 B50D 79E3 39D3  721C EB3E 94AD BE12 29CF
  storage:
    layout:
      name: lvm
      password: ubuntu
  timezone: "Europe/Lisbon"
  keyboard:
    layout: pt
  locale: en_US
  ssh:
    install-server: no
  packages:
    - curl
    - wget
    - gpg
    - software-properties-common
    - apt-transport-https 
    - ca-certificates
    - libpam-pwquality
    - microsoft-edge-stable 
    - intune-portal
  snaps:
    - name: code
      classic: true
    - name: powershell
      classic: true
  debconf-selections: |
     ufw ufw/enable boolean true
  late-commands:
    - curtin in-target --target=/target -- sh -c 'sed -i -e "s/pam_pwquality.so retry=3/pam_pwquality.so retry=3 dcredit=-1 ocredit=-1 ucredit=-1 lcredit=-1 minlen=12/g" /etc/pam.d/common-password'
    - curtin in-target --target=/target -- sh -c 'touch /etc/dconf/profile/user'
    - | 
      cat << EOF > /target/etc/dconf/profile/user
      user-db:user
      system-db:local
      EOF
    - curtin in-target --target=/target -- sh -c 'mkdir -p /etc/dconf/db/local.d/'
    - | 
      cat << EOF > /target/etc/dconf/db/local.d/00-favorite-apps 
      [org/gnome/shell]
      favorite-apps = ['microsoft-edge.desktop', 'intune-portal.desktop', 'code_code.desktop', 'snap-store_snap-store.desktop', 'org.gnome.Terminal.desktop', 'powershell_powershell.desktop', 'org.gnome.Nautilus.desktop']
      EOF
    - curtin in-target --target=/target -- sh -c 'dconf update'
    - curtin in-target --target=/target -- sh -c 'if [ -e /etc/apt/sources.list.d/microsoft-edge.list ]; then rm -f /etc/apt/sources.list.d/microsoft-edge.list; fi'
    - curtin in-target --target=/target -- apt update && apt dist-upgrade -y
    - curtin in-target --target=/target -- apt autoremove -y
    - curtin in-target --target=/target -- apt autoclean